export enum EAccent {
  PRIMARY = "PRIMARY",
  SECONDARY = "SECONDARY"
}

// Colors available in the app
export enum EColor {
  WHITE = "WHITE",
  RHYTM = "RHYTM",
  BLUE_BELL = "BLUE_BELL",
  PURPLE_NAVY = "PURPLE_NAVY",
  TIFFANY_BLUE = "TIFFANY_BLUE",
  YANKES_BLUE = "YANKES_BLUE",
  YANKES_BLUE_LIGHTER = "YANKES_BLUE_LIGHTER",
  SPACE_CADET = "SPACE_CADET",
  JACARTA = "JACARTA",
  AMERICAN_BLUE = "AMERICAN_BLUE",
  DARK_JUNGLE_GREEN = "DARK_JUNGLE_GREEN",
  RED = "RED"
}

export enum EFontFamily {
  TITILLIUM_WEB = "TITILLIUM_WEB"
}

export enum EFontWeight {
  LIGHT = "LIGHT",
  REGULAR = "REGULAR",
  SEMI_BOLD = "SEMI_BOLD",
  BOLD = "BOLD"
}
