name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest

    container:
      image: node:14

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --force

  lint:
    runs-on: ubuntu-latest
    needs: dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Typescript code passes lint check
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Code builds successfully
        run: yarn build
